#!/usr/bin/env bash
set -Eeuo pipefail

# Host maintenance for SEP. This script intentionally does not run
# `docker system prune -a` and never removes Docker volumes.

LOCK_FILE="${SEP_MAINTENANCE_LOCK:-/run/lock/sep-maintenance.lock}"
DEPLOY_LOCK_FILE="${SEP_DEPLOY_LOCK_FILE:-/opt/sep/.deploy.lock}"
LOG_FILE="${SEP_MAINTENANCE_LOG:-/var/log/sep-maintenance.log}"
MOUNT_POINT="${SEP_MAINTENANCE_MOUNT:-/}"
WARN_PERCENT="${SEP_MAINTENANCE_WARN_PERCENT:-75}"
CRITICAL_PERCENT="${SEP_MAINTENANCE_CRITICAL_PERCENT:-85}"
BUILD_CACHE_AGE="${SEP_BUILD_CACHE_AGE:-168h}"
BUILD_CACHE_KEEP_STORAGE="${SEP_BUILD_CACHE_KEEP_STORAGE:-20GB}"
JOURNAL_RETENTION="${SEP_JOURNAL_RETENTION:-14d}"
JOURNAL_MAX_SIZE="${SEP_JOURNAL_MAX_SIZE:-500M}"

mkdir -p "$(dirname "$LOCK_FILE")" "$(dirname "$DEPLOY_LOCK_FILE")" "$(dirname "$LOG_FILE")"
exec 9>"$LOCK_FILE"
flock -n 9 || exit 0
# Do not reclaim cache while SEP is building or switching application versions.
exec 8>"$DEPLOY_LOCK_FILE"
flock -n 8 || exit 0
exec > >(tee -a "$LOG_FILE") 2>&1

timestamp() { date -u '+%Y-%m-%dT%H:%M:%SZ'; }
log() { printf '[%s] %s\n' "$(timestamp)" "$*"; logger -t sep-maintenance -- "$*" 2>/dev/null || true; }

disk_percent() {
  df -P "$MOUNT_POINT" | awk 'NR == 2 { gsub(/%/, "", $5); print $5 }'
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || { log "missing command: $1"; exit 1; }
}

require_command docker
require_command journalctl
require_command flock

before="$(disk_percent)"
log "maintenance started mount=$MOUNT_POINT usage=${before}% build_cache_age=$BUILD_CACHE_AGE"

if (( before >= WARN_PERCENT )); then
  log "disk usage is above warning threshold (${WARN_PERCENT}%)"
fi

# BuildKit cache is reproducible and can be regenerated by the next deploy.
# Keep the recent window warm; remove only cache records older than the window.
if (( before >= CRITICAL_PERCENT )); then
  log "disk usage is above critical threshold (${CRITICAL_PERCENT}%); pruning reclaimable BuildKit cache, keep_storage=$BUILD_CACHE_KEEP_STORAGE"
  docker builder prune -af --keep-storage "$BUILD_CACHE_KEEP_STORAGE"
else
  docker builder prune -af --filter "until=$BUILD_CACHE_AGE" --keep-storage "$BUILD_CACHE_KEEP_STORAGE"
fi

# Stopped application containers preserve exact rollback image/configuration.
# Intentionally stopped services (for example Ollama) must also remain available
# for a later docker start. Never globally prune stopped containers here.

# Bound host journal growth. Docker JSON logs are already capped by Compose
# max-size/max-file settings and are intentionally not truncated here.
journalctl --vacuum-time="$JOURNAL_RETENTION" --vacuum-size="$JOURNAL_MAX_SIZE"

after="$(disk_percent)"
log "maintenance finished usage=${after}%"

if (( after >= CRITICAL_PERCENT )); then
  log "CRITICAL: disk usage remains at ${after}%, manual investigation required"
  exit 2
fi

if (( after >= WARN_PERCENT )); then
  log "WARNING: disk usage remains above ${WARN_PERCENT}%; inspect docker system df and backups"
fi
