import { z } from 'zod';

export const TaskRunStatusSchema = z.enum(['draft','awaiting_confirmation','running','completed','failed','stopped']);
export const TaskStepStatusSchema = z.enum(['queued','running','completed','failed','skipped']);
export const CapabilityTypeSchema = z.enum(['AGENT','RPA','SKILL','AI_APP']);
const EmployeeSchema = z.object({ id:z.string(), name:z.string(), description:z.string(), position:z.string(), industry:z.string(), avatar:z.string().nullable(), capabilities:z.array(z.object({id:z.string(),name:z.string(),description:z.string(),type:CapabilityTypeSchema})) });
export const TaskStepSchema = z.object({ id:z.string().min(1), order:z.number().int(), title:z.string(), description:z.string(), intent:z.string(), employee:EmployeeSchema, capability:z.object({id:z.string(),name:z.string(),description:z.string(),type:CapabilityTypeSchema}), dependsOn:z.array(z.string()), rationale:z.string(), estimatedSeconds:z.number(), status:TaskStepStatusSchema, progress:z.number().min(0).max(100), output:z.string().max(200000).optional(), error:z.string().optional(), startedAt:z.string().datetime().optional(), completedAt:z.string().datetime().optional(), durationMs:z.number().nonnegative().optional() });
export const StepsSchema = z.array(TaskStepSchema).min(1).max(50).superRefine((steps,ctx)=>{ const ids=new Set(steps.map(s=>s.id)); steps.forEach((s,i)=>s.dependsOn.forEach(d=>{if(!ids.has(d))ctx.addIssue({code:z.ZodIssueCode.custom,path:[i,'dependsOn'],message:`unknown dependency ${d}`});})); }).refine(v=>JSON.stringify(v).length<=2*1024*1024,'steps payload exceeds 2MB');
const CoordinateSchema = z.object({x:z.number().finite().min(-10000).max(10000),y:z.number().finite().min(-10000).max(10000)}).strict();
export const LayoutSchema = z.object({nodes:z.record(CoordinateSchema).default({}),endpoints:z.object({input:CoordinateSchema.optional(),output:CoordinateSchema.optional()}).strict().optional()}).strict();
export const PlannerSchema = z.object({type:z.string(),model:z.string()}).passthrough();
export const CreateTaskDtoSchema = z.object({objective:z.string().trim().min(1).max(4000),summary:z.string().optional(),steps:StepsSchema,layout:LayoutSchema.nullable().optional(),planner:PlannerSchema.optional(),status:TaskRunStatusSchema.optional()}).strict();
export const UpdateTaskDtoSchema = z.object({status:TaskRunStatusSchema.optional(),steps:StepsSchema.optional(),layout:LayoutSchema.nullable().optional(),startedAt:z.string().datetime().nullable().optional(),completedAt:z.string().datetime().nullable().optional(),expectedUpdatedAt:z.string().datetime().optional()}).strict();
export const StepPatchDtoSchema = z.object({status:TaskStepStatusSchema.optional(),progress:z.number().min(0).max(100).optional(),output:z.string().max(200000).optional(),error:z.string().optional(),startedAt:z.string().datetime().nullable().optional(),completedAt:z.string().datetime().nullable().optional(),durationMs:z.number().nonnegative().optional(),expectedUpdatedAt:z.string().datetime().optional()}).strict();
export const CreateTemplateDtoSchema = z.object({name:z.string().trim().min(1).max(64),objective:z.string().trim().min(1).max(4000),steps:StepsSchema,layout:LayoutSchema.nullable().optional()}).strict();
export const TaskQuerySchema = z.object({limit:z.coerce.number().int().min(1).max(200).default(50),cursor:z.string().optional(),scope:z.enum(['mine','enterprise']).default('mine'),status:z.union([TaskRunStatusSchema,z.array(TaskRunStatusSchema)]).optional()});
export type CreateTaskDto=z.infer<typeof CreateTaskDtoSchema>; export type UpdateTaskDto=z.infer<typeof UpdateTaskDtoSchema>; export type StepPatchDto=z.infer<typeof StepPatchDtoSchema>; export type CreateTemplateDto=z.infer<typeof CreateTemplateDtoSchema>; export type TaskQuery=z.infer<typeof TaskQuerySchema>;
