import { ConflictException, ForbiddenException, NotFoundException } from '@nestjs/common';
import { TaskService } from './task.service';

const step=(id:string,status='queued')=>({id,order:0,title:id,description:'',intent:'',employee:{id:'e',name:'员工',description:'',position:'',industry:'',avatar:null,capabilities:[]},capability:{id:'c',name:'能力',description:'',type:'agent'},dependsOn:[],rationale:'',estimatedSeconds:1,status,progress:0});
const base={id:'t1',objective:'目标',summary:'',status:'AWAITING_CONFIRMATION',steps:[step('s1')],layout:null,planner:null,userId:'u1',enterpriseId:'ent',createdAt:new Date('2026-01-01'),updatedAt:new Date('2026-01-01')};

describe('TaskService',()=>{
 let prisma:any; let service:TaskService;
 beforeEach(()=>{prisma={enterpriseMember:{findFirst:jest.fn().mockResolvedValue({enterpriseId:'ent',role:'ENTERPRISE_ADMIN'})},taskRun:{findUnique:jest.fn().mockResolvedValue(base),findMany:jest.fn(),create:jest.fn().mockResolvedValue(base),update:jest.fn().mockImplementation(({data}:any)=>({...base,...data,updatedAt:new Date()})),updateMany:jest.fn().mockResolvedValue({count:1}),findUniqueOrThrow:jest.fn().mockResolvedValue({...base,status:'RUNNING'}),delete:jest.fn()},taskRunEvent:{create:jest.fn(),createMany:jest.fn()},taskTemplate:{findUnique:jest.fn(),findMany:jest.fn(),create:jest.fn(),delete:jest.fn()}}; service=new TaskService(prisma);});
 it('rejects dangling dependencies and out-of-range layout',()=>{expect(()=>require('shared').StepsSchema.parse([{...step('s1'),dependsOn:['missing']}])).toThrow(); expect(()=>require('shared').LayoutSchema.parse({nodes:{s1:{x:10001,y:0}}})).toThrow();});
 it('maps status and derives events',async()=>{await service.create('u1',{objective:'x',steps:[step('s1')],status:'awaiting_confirmation'} as any); expect(prisma.taskRunEvent.create).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({type:'RUN_CREATED'})})); prisma.taskRun.findUnique.mockResolvedValue({...base,steps:[step('s1')],status:'AWAITING_CONFIRMATION'}); await service.update('t1','u1',{steps:[step('s1','running')]} as any); expect(prisma.taskRunEvent.createMany).toHaveBeenCalledWith({data:expect.arrayContaining([expect.objectContaining({type:'STEP_STARTED'})])});});
 it('serializes task run responses with summary fields',async()=>{const created=await service.create('u1',{objective:'x',steps:[step('s1')],status:'awaiting_confirmation'} as any); expect(created).toMatchObject({stepCount:1,completedStepCount:0,employeeNames:['员工'],summary:'',steps:expect.any(Array),layout:null,planner:null}); prisma.taskRun.findUnique.mockResolvedValue({...base,steps:[step('s1','completed')],status:'COMPLETED'}); const patched=await service.patchStep('t1','u1','s1',{status:'completed'} as any); expect(patched).toMatchObject({stepCount:1,completedStepCount:1,employeeNames:['员工'],summary:''});});
 it('rejects another owner with 404',async()=>{prisma.taskRun.findUnique.mockResolvedValue({...base,userId:'other'}); await expect(service.get('t1','u1')).rejects.toBeInstanceOf(NotFoundException);});
 it('step patch only changes target and optimistic conflict is 409',async()=>{await service.patchStep('t1','u1','s1',{status:'completed'} as any); expect(prisma.taskRun.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({steps:expect.arrayContaining([expect.objectContaining({status:'completed'})])})})); prisma.taskRun.findUnique.mockResolvedValue({...base,updatedAt:new Date('2026-01-02')}); await expect(service.update('t1','u1',{expectedUpdatedAt:'2026-01-01'} as any)).rejects.toBeInstanceOf(ConflictException);});
 it('enterprise scope requires admin and cursor pagination',async()=>{prisma.enterpriseMember.findFirst.mockResolvedValue({enterpriseId:'ent',role:'MEMBER'}); await expect(service.list('u1',{scope:'enterprise',limit:1} as any)).rejects.toBeInstanceOf(ForbiddenException); prisma.enterpriseMember.findFirst.mockResolvedValue({enterpriseId:'ent',role:'ENTERPRISE_ADMIN'}); prisma.taskRun.findMany.mockResolvedValue([{...base},{...base,id:'t2',createdAt:new Date('2025-01-01')}]); const result=await service.list('u1',{scope:'enterprise',limit:1} as any); expect(result.nextCursor).toBe('t1');});
 it('reconciles only runs older than ten minutes',async()=>{prisma.taskRun.findUnique.mockResolvedValue({...base,status:'RUNNING',updatedAt:new Date(Date.now()-11*60*1000),steps:[step('s1','running')]}); await service.reconcile('t1','u1'); expect(prisma.taskRun.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({status:'STOPPED'})}));});
});
